[{if $sPaymentID == "wcs_ccard" || $sPaymentID == "wcs_ccard-moto"}]
    [{include file="wcs_payment_ccard.tpl"}]
[{elseif $sPaymentID == "wcs_eps"}]
    [{include file="wcs_payment_eps.tpl"}]
[{elseif $sPaymentID == "wcs_giropay"}]
    [{include file="wcs_payment_giropay.tpl"}]
[{elseif $sPaymentID == "wcs_idl"}]
    [{include file="wcs_payment_idl.tpl"}]
[{elseif $sPaymentID == "wcs_installment"}]
    [{include file="wcs_payment_installment.tpl"}]
[{elseif $sPaymentID == "wcs_invoice_b2b" || $sPaymentID == "wcs_invoice_b2c"}]
    [{include file="wcs_payment_invoice.tpl"}]
[{elseif $sPaymentID == "wcs_pbx"}]
    [{include file="wcs_payment_pbx.tpl"}]
[{elseif $sPaymentID == "wcs_sepa-dd"}]
    [{include file="wcs_payment_sepa_dd.tpl"}]
[{elseif $sPaymentID == "wcs_trustpay"}]
    [{include file="wcs_payment_trustpay.tpl"}]
[{elseif $sPaymentID == "wcs_voucher"}]
    [{include file="wcs_payment_voucher.tpl"}]
[{elseif $oView->isWcsPaymethod($sPaymentID)}]
    [{include file="wcs_payment_other.tpl"}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]