<?php
/**
 * Shop System Plugins
 * - Terms of use can be found under
 * https://guides.qenta.com/shop_plugins:info
 * - License can be found under:
 * https://github.com/qenta-cee/oxid-qcs/blob/master/LICENSE
*/

$sLangName = "Deutsch";

$aLang = array(
    "charset" => "UTF-8",
    "qentacheckoutseamless" => "QENTA Checkout Seamless",
    'SHOP_MODULE_GROUP_qcs_params' => 'Allgemeine Einstellungen',
    'SHOP_MODULE_GROUP_qcs_plugin' => 'Plugin Einstellungen',
    'SHOP_MODULE_GROUP_qcs_risk_settings' => 'Fraud Prevention Suite',
    'SHOP_MODULE_GROUP_qcs_invoice_settings' => 'Kauf auf Rechnung Einstellungen',
    'SHOP_MODULE_GROUP_qcs_installment_settings' => 'Kauf auf Raten Einstellungen',
    'SHOP_MODULE_GROUP_qcs_pci_dss' => 'PCI DSS/Kreditkarten Einstellungen',
    'SHOP_MODULE_sCustomerId' => 'Kundennummer',
    'HELP_SHOP_MODULE_sCustomerId' => 'Ihre QENTA-Kundennummer (customerId, im Format D2#####).<br /><a href="https://guides.qenta.com/request_parameters#customerid" target="_blank">Weitere Informationen: customerId</a>',
    'SHOP_MODULE_sShopId' => 'Shop ID',
    'HELP_SHOP_MODULE_sShopId' => 'Shop-Kennung bei mehreren Onlineshops.<br />Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/support" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.<br /><a href="https://guides.qenta.com/request_parameters#shopid" target="_blank">Weitere Informationen: shopId</a>',
    'SHOP_MODULE_sSecret' => 'Secret',
    'HELP_SHOP_MODULE_sSecret' => 'Geheime Zeichenfolge, die Sie von QENTA erhalten haben, zum Signieren und Validieren von Daten zur Pr&uuml;fung der Authentizit&auml;t.<br /><a href="https://guides.qenta.com/request_parameters#customerid" target="_blank">Weitere Informationen: secret</a>',
    'SHOP_MODULE_sPassword' => 'Back-end-Passwort',
    'HELP_SHOP_MODULE_sPassword' => 'Passwort f&uuml;r back-end Operationen (Toolkit).',
    'SHOP_MODULE_sServiceUrl' => 'URL zur Impressum-Seite',
    'HELP_SHOP_MODULE_sServiceUrl' => 'URL auf der Bezahlseite, die zur Impressum-Seite des Onlineshops f&uuml;hrt.<a href="https://guides.qenta.com/request_parameters#serviceurl" target="_blank">Weitere Informationen: serviceUrl</a>',
    'SHOP_MODULE_bAutoDeposit' => 'Automatisches Abbuchen',
    'HELP_SHOP_MODULE_bAutoDeposit' => 'Automatisches Abbuchen der Zahlungen bei Tagesabschluss. Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/support" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.<br /><a href="https://guides.qenta.com/request_parameters#autodeposit" target="_blank">Weitere Informationen: autoDeposit</a>',
    'SHOP_MODULE_sIframeCssUrl' => 'iFrame CSS-URL',
    'HELP_SHOP_MODULE_sIframeCssUrl' => 'Vollst&auml;ndige URL auf eine CSS-Datei, um die iFrame-Eingabefelder anzupassen, wenn das "PCI DSS SAQ A Compliance"-Feature verwendet wird. <a href="https://guides.qenta.com/qcs:pci3_fallback:start#customization_via_css" target="_blank">More information</a>',
    'SHOP_MODULE_sConfirmMail' => 'Benachrichtigungsmail',
    'HELP_SHOP_MODULE_sConfirmMail' => 'Benachrichtigung per E-Mail &uuml;ber Zahlungen Ihrer Kunden, falls ein Kommunikationsproblem zwischen QENTA und Ihrem Onlineshop aufgetreten ist. <a href="https://guides.qenta.com/request_parameters#confirmMail" target="_blank">Weitere Informationen</a>. Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/sales" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.',
    'SHOP_MODULE_bDuplicateRequestCheck' => '&Uuml;berpr&uuml;fung auf doppelte Anfragen',
    'HELP_SHOP_MODULE_bDuplicateRequestCheck' => '&Uuml;berpr&uuml;fung auf mehrfache Anfragen seitens Ihres Kunden.<a href="https://guides.qenta.com/request_parameters#duplicaterequestcheck" target="_blank">Weitere Informationen: duplicateRequestCheck</a>',
    'SHOP_MODULE_sPluginMode' => 'Plugin Modus',
    'SHOP_MODULE_sPluginMode_Demo' => 'Demo',
    'SHOP_MODULE_sPluginMode_Test' => 'Test',
    'SHOP_MODULE_sPluginMode_Live' => 'Production',
    'HELP_SHOP_MODULE_sPluginMode' => 'Zum Testen der Integration eine vordefinierte Konfiguration ausw&auml;hlen. F&uuml;r Produktivsysteme "Production" ausw&auml;hlen.',
    'SHOP_MODULE_bUseIframe' => 'Seite von Finanzdienstleistern in iFrame anzeigen',
    'HELP_SHOP_MODULE_bUseIframe' => 'Andernfalls wird Ihr Konsument auf diese Seite weitergeleitet und danach zur&uuml;ck zu Ihrem Onlineshop geleitet.',
    'SHOP_MODULE_sDeleteFailedOrCanceledOrders' => 'Bestellungen bei fehlgeschlagener oder abgebrochener Zahlung löschen',
    'HELP_SHOP_MODULE_sDeleteFailedOrCanceledOrders' => 'Falls aktiviert, werden die Bestellungen bei fehlgeschlagener oder abgebrochener Zahlung gelöscht. Achtung: Diese Einstellung gilt für alle QENTA-Zahlungsmittel.',
    'SHOP_MODULE_bDssSaqAEnable' => 'SAQ A konform',
    'HELP_SHOP_MODULE_bDssSaqAEnable' => 'Falls kein H&auml;kchen gesetzt ist, gilt der strengere SAQ A-EP. Falls ein H&auml;kchen gesetzt ist, wird in QENTA Checkout Seamless das "PCI DSS SAQ A Compliance"-Feature verwendet und es gilt der SAQ A. <a href="https://guides.qenta.com/qcs:pci3_fallback:start" target="_blank">Weitere Informationen</a>',
    'SHOP_MODULE_bShowCreditcardCardholder' => 'Feld f&uuml;r Karteninhaber anzeigen',
    'HELP_SHOP_MODULE_bShowCreditcardCardholder' => 'Anzeige des Feldes zur Eingabe des Kreditkarteninhabers im Formular w&auml;hrend des Bezahlvorganges.',
    'SHOP_MODULE_bShowCreditcardCvc' => 'Feld f&uuml;r CVC anzeigen',
    'HELP_SHOP_MODULE_bShowCreditcardCvc' => 'Anzeige des Feldes zur Eingabe der Kreditkartenpr&uuml;fnummer (CVC) im Formular w&auml;hrend des Bezahlvorganges.',
    'SHOP_MODULE_bShowCreditcardIssueDate' => 'Feld f&uuml;r Ausgabedatum anzeigen',
    'HELP_SHOP_MODULE_bShowCreditcardIssueDate' => 'Anzeige des Feldes zur Eingabe des Kreditkarten-Ausgabedatums im Formular w&auml;hrend des Bezahlvorganges.',
    'SHOP_MODULE_bShowCreditcardIssueNumber' => 'Feld f&uuml;r Ausgabenummer anzeigen',
    'HELP_SHOP_MODULE_bShowCreditcardIssueNumber' => 'Anzeige des Feldes zur Eingabe der Kreditkarten-Ausgabenummer im Formular w&auml;hrend des Bezahlvorganges.',
    'SHOP_MODULE_bSendAdditionalCustomerBilling' => 'Verrechnungsdaten des Konsumenten mitsenden',
    'HELP_SHOP_MODULE_bSendAdditionalCustomerBilling' => 'Weiterleitung der Rechnungsdaten des Kunden an den Finanzdienstleister.',
    'SHOP_MODULE_bSendAdditionalCustomerShipping' => 'Versanddaten des Konsumenten mitsenden',
    'HELP_SHOP_MODULE_bSendAdditionalCustomerShipping' => 'Weiterleitung der Versanddaten des Kunden an den Finanzdienstleister.',
    'SHOP_MODULE_bSendAdditionalBasketData' => 'Warenkorbdaten mitsenden',
    'HELP_SHOP_MODULE_bSendAdditionalBasketData' => 'Weiterleitung des Warenkorbs des Kunden an den Finanzdienstleister.',
    'SHOP_MODULE_sShopName' => 'Shop-Pr&auml;fix im Buchungstext',
    'HELP_SHOP_MODULE_sShopName' => 'Referenz zu Ihrem Onlineshop im Buchungstext f&uuml;r Ihren Kunden, max. 9 Zeichen (wird zusammen mit der Auftragsnummer zum Erstellen des Parameters <a href="https://guides.qenta.com/request_parameters#customerstatement" target="_blank">customerStatement</a>  verwendet).',
    'SHOP_MODULE_sInvoicePayolutionMId' => 'payolution mID',
    'HELP_SHOP_MODULE_sInvoicePayolutionMId' => 'Ihre payolution H&auml;ndler ID, nicht-base64-encoded.',
    'SHOP_MODULE_bInvoiceAllowDifferingAddresses' => 'Rechnungs/Versandadresse m&uuml;ssen ident sein',
    'SHOP_MODULE_bInvoiceb2bTrustedShopsCheckbox' => 'payolution Nutzungsbedingungen f&uuml;r Kauf auf Rechnung B2B',
    'SHOP_MODULE_bInvoiceb2cTrustedShopsCheckbox' => 'payolution Nutzungsbedingungen f&uuml;r Kauf auf Rechnung B2C',
    'SHOP_MODULE_bInstallmentTrustedShopsCheckbox' => 'payolution Nutzungsbedingungen f&uuml;r Kauf auf Raten',
    'SHOP_MODULE_sInvoiceProvider' => 'Provider f&uuml;r Kauf auf Rechnung',
    'SHOP_MODULE_sInvoiceProvider_RATEPAY' => 'Ratepay',
    'SHOP_MODULE_sInvoiceProvider_PAYOLUTION' => 'payolution',
    'SHOP_MODULE_sInvoiceProvider_QENTA' => 'QENTA',
    'SHOP_MODULE_sInstallmentProvider' => 'Provider f&uuml;r Kauf auf Raten',
    'SHOP_MODULE_sInstallmentProvider_RATEPAY' => 'Ratepay',
    'SHOP_MODULE_sInstallmentProvider_PAYOLUTION' => 'payolution',
    'SHOP_MODULE_sInstallmentPayolutionMId' => 'payolution mID',
    'HELP_SHOP_MODULE_sInstallmentPayolutionMId' => 'Ihre payolution H&auml;ndler ID, nicht-base64-encoded.',
    'SHOP_MODULE_bInstallmentAllowDifferingAddresses' => 'Rechnungs/Versandadresse m&uuml;ssen ident sein',
    'SHOP_MODULE_bRiskSuppress' => 'Fraud Prevention Suite aktivieren',
    'HELP_SHOP_MODULE_bRiskSuppress' => 'Deaktivieren der Fraud Prevention Suite (FPS). Die FPS muss explizit von unseren <a href="https://guides.qenta.com/support" target="_blank">Sales-Teams</a> freigeschalten werden. <a href="https://guides.qenta.com/request_parameters#risksuppress" target="_blank">Weitere Informationen</a>',
    'SHOP_MODULE_sRiskConfigAlias' => 'Regel f&uuml;r Fraud Prevention Suite',
    'HELP_SHOP_MODULE_sRiskConfigAlias' => 'Auswahl einer spezifischen Regel f&uuml;r die QENTA Fraud Prevention Suite (FPS). <a href="https://guides.qenta.com/request_parameters#riskconfigalias" target="_blank">Weitere Informationen: riskConfigAlias</a> <br />Bitte kontaktieren Sie unsere <a href="https://guides.qenta.com/support" target="_blank">Sales-Teams</a> um dieses Feature freizuschalten.',
    'QENTA_CHECKOUT_SEAMLESS_BANCONTACT_MISTERCASH_LABEL' => 'Bancontact',
    'QENTA_CHECKOUT_SEAMLESS_CCARD_LABEL' => 'Kreditkarte',
    'QENTA_CHECKOUT_SEAMLESS_CCARD-MOTO_LABEL' => 'Kreditkarte Mail Order / Telephone Order',
    'QENTA_CHECKOUT_SEAMLESS_EKONTO_LABEL' => 'eKonto',
    'QENTA_CHECKOUT_SEAMLESS_EPAY_BG_LABEL' => 'ePay.bg',
    'QENTA_CHECKOUT_SEAMLESS_EPS_LABEL' => 'eps Online-Überweisung',
    'QENTA_CHECKOUT_SEAMLESS_GIROPAY_LABEL' => 'giropay',
    'QENTA_CHECKOUT_SEAMLESS_IDL_LABEL' => 'iDEAL',
    'QENTA_CHECKOUT_SEAMLESS_INSTALLMENT_LABEL' => 'Kauf auf Raten',
    'QENTA_CHECKOUT_SEAMLESS_INVOICE_B2B_LABEL' => 'Kauf auf Rechnung B2B',
    'QENTA_CHECKOUT_SEAMLESS_INVOICE_B2C_LABEL' => 'Kauf auf Rechnung B2C',
    'QENTA_CHECKOUT_SEAMLESS_MONETA_LABEL' => 'moneta.ru',
    'QENTA_CHECKOUT_SEAMLESS_PAYPAL_LABEL' => 'PayPal',
    'QENTA_CHECKOUT_SEAMLESS_PBX_LABEL' => 'paybox',
    'QENTA_CHECKOUT_SEAMLESS_POLI_LABEL' => 'POLi',
    'QENTA_CHECKOUT_SEAMLESS_PRZELEWY24_LABEL' => 'Przelewy24',
    'QENTA_CHECKOUT_SEAMLESS_PSC_LABEL' => 'paysafecard',
    'QENTA_CHECKOUT_SEAMLESS_SELECT_LABEL' => 'Zahlungsmittelauswahl',
    'QENTA_CHECKOUT_SEAMLESS_SEPA-DD_LABEL' => 'SEPA Lastschrift',
    'QENTA_CHECKOUT_SEAMLESS_SKRILLWALLET_LABEL' => 'Skrill Digital Wallet',
    'QENTA_CHECKOUT_SEAMLESS_SOFORTUEBERWEISUNG_LABEL' => 'Sofort.',
    'QENTA_CHECKOUT_SEAMLESS_TATRAPAY_LABEL' => 'TatraPay',
    'QENTA_CHECKOUT_SEAMLESS_TRUSTLY_LABEL' => 'Trustly',
    'QENTA_CHECKOUT_SEAMLESS_VOUCHER_LABEL' => 'Mein Gutschein',
    'QENTA_CHECKOUT_SEAMLESS_TRUSTPAY_LABEL' => 'TrustPay',
    'QENTA_CHECKOUT_SEAMLESS_SKRILLDIRECT_LABEL' => 'Skrill Direct',
    'QENTA_CHECKOUT_SEAMLESS_MPASS_LABEL' => 'Masterpass',
    'QENTA_CHECKOUT_SEAMLESS_BANCONTACT_MISTERCASH_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_CCARD_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_CCARD-MOTO_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_EKONTO_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_EPAY_BG_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_EPS_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_GIROPAY_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_IDL_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_INSTALLMENT_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_INVOICE_B2B_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_INVOICE_B2C_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_MONETA_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_MPASS_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_PAYPAL_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_PBX_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_POLI_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_PRZELEWY24_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_PSC_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_SELECT_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_SEPA-DD_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_SKRILLDIRECT_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_SKRILLWALLET_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_SOFORTUEBERWEISUNG_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_TATRAPAY_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_TRUSTLY_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_VOUCHER_DESC' => '',
    'QENTA_CHECKOUT_SEAMLESS_TRUSTPAY_DESC' => '',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_CONSUMERCOMPANYNAME' => 'Firmennamen des Kunden',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_AMOUNT' => 'Betrag',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_CURRENCY' => 'W&auml;hrung',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_FINANCIALINSTITUTION' => 'Finanzinstitut',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_ORDERNUMBER' => 'QENTA Auftragsnummer',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYMENTSTATE' => 'Bezahlstatus',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_GATEWAYCONTRACTNUMBER' => 'Gateway Vertragsnummer',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_GATEWAYREFERENCENUMBER' => 'Gateway Referenznummer',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_MASKEDPAN' => 'Kreditkarte anonymisiert',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_EXPIRY' => 'Kreditkarte g&uuml;ltig bis',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_CARDHOLDER' => 'Kreditkarte Karteninhaber',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_AUTHENTICATED' => 'Authorisiert',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERID' => 'PayPal Bezahlender ID',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYEREMAIL' => 'PayPal Bezahlender E-Mail',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERFIRSTNAME' => 'PayPal Bezahlender Vorname',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERLASTNAME' => 'PayPal Bezahlender Nachname',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERADDRESSNAME' => 'PayPal Bezahlender Adresse',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERADDRESSCOUNTRY' => 'PayPal Bezahlender Land',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERADDRESSCOUNTRYCODE' => 'PayPal Bezahlender L&auml;ndercode',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERADDRESSCITY' => 'PayPal Bezahlender Stadt',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERADDRESSSTATE' => 'PayPal Bezahlender Bundesland',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERADDRESSSTREET1' => 'PayPal Bezahlender Straße',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERADDRESSSTREET2' => 'PayPal Bezahlender Hausnummer',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PAYPALPAYERADDRESSZIP' => 'PayPal Bezahlender Postleitzahl',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_CONSUMERNAME' => 'iDEAL Konsument Name',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_CONSUMERACCOUNTNUMBER' => 'iDEAL Konsument Kontonummer',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_CONSUMERCITY' => 'iDEAL Konsument Stadt',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SOFORTSENDERACCOUNTOWNER' => 'Sofort. Sender Kontoinhaber',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SENDERACCOUNTNUMBER' => 'Sofort. Sender Kontonummer',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SENDERBANKNUMBER' => 'Sofort. Sender Bankleitzahl',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SENDERBANKNAME' => 'Sofort. Sender Bank',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SENDERBIC' => 'Sofort. Sender BIC',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SENDERIBAN' => 'Sofort. Sender IBAN',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SENDERCOUNTRY' => 'Sofort. Sender Land',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SENDERCRITERIA' => 'Sofort. Sender Kriterien',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_MANDATEID' => 'SEPA Mandat-ID',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_MANDATESIGNATUREDATE' => 'SEPA Mandat Unterschriftsdatum',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_CREDITORID' => 'SEPA Kreditor-ID',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_DUEDATE' => 'SEPA F&auml;lligkeit',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_LANGUAGE' => 'Sprache',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_MESSAGE' => 'Nachricht',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_LIABILITYSHIFTINDICATOR' => 'liabilityShiftIndicator',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_INSTRUMENTCOUNTRY' => 'instrumentCountry',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_RISKINTERCEPT' => 'riskIntercept',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_RISKREASONCODE' => 'riskReasonCode',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_RISKREASONMESSAGE' => 'riskReasonMessage',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_RISKRETURNCODE' => 'riskReturnCode',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_RISKRETURNMESSAGE' => 'riskReturnMessage',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_CHECKOUTTYPE' => 'checkoutType',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_AVSRESPONSECODE' => 'avsResponseCode',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_AVSRESPONSEMESSAGE' => 'avsResponseMessage',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_AVSPROVIDERRESULTCODE' => 'avsProviderResultCode',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_AVSPROVIDERRESULTMESSAGE' => 'avsProviderResultMessage',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_IDEALCONSUMERNAME' => 'idealConsumerName',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_IDEALCONSUMERBIC' => 'idealConsumerBIC',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_IDEALCONSUMERCITY' => 'idealConsumerCity',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_IDEALCONSUMERIBAN' => 'idealConsumerIBAN',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_IDEALCONSUMERACCOUNTNUMBER' => 'idealConsumerAccountNumber',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SENDERACCOUNTOWNER' => 'senderAccountOwner',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_SECURITYCRITERIA' => 'securityCriteria',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_ANONYMOUSPAN' => 'anonymousPan',
    'QCS_SUBMIT' => 'Senden',
    'QCS_SUBMIT_CONFIG' => 'QENTA Checkout Seamless Konfiguration senden',
    'MODULE_PAYMENT_QCS_EXPORT_CONFIG_RECEIVER' => 'Empf&auml;nger',
    'MODULE_PAYMENT_QCS_EXPORT_CONFIG_CONFIG_STRING' => 'Konfiguration',
    'MODULE_PAYMENT_QCS_EXPORT_CONFIG_DESC_TEXT' => 'Kommentar',
    'MODULE_PAYMENT_QCS_EXPORT_CONFIG_RETURN_MAIL' => 'Antwort E-Mail-Adresse',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PROVIDERREFERENCENUMBER': 'Referenznummer des Anbieters',
    'ORDER_OVERVIEW_QENTA_CHECKOUT_SEAMLESS_PROVIDERCONTRACTNUMBER': 'Vertragsnummer des Anbieters'
);
